GOOGLE_APPLICATION_CREDENTIALS="../../../.secrets/google.token"
PYTHONPATH=$(PYTHONPATH):../src

all:
	poetry run python src/writeTxt.py input output > logs/info.log


%:
	poetry run python src/writeTxt.py input/{{org_code}}-$@.pdf output/{{org_code}}-$@.pdf.doc.json
